---
- name: Deploy TODO App
  hosts: all
  become: true
  vars:
    app_repo: "https://github.com/olugbedu/DevOps-Stage-4.git"
    app_dir: "/opt/todo-app"
    domain: "gbedu.name.ng"
  
  roles:
    - setup
    - deploy
