name: Deploy and Configure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

    #   - name: SSH into EC2
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.ELASTIC_IP }}
    #       username: ubuntu
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         ansible --version
    #         ansible-playbook -i ansible/inventory.yaml ansible/playbook.yaml --extra-vars '@ansible/terraform_vars.yml'
      - name: Run Ansible Playbook
        run: |
          ansible --version
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deji_new
          chmod 600 ~/.ssh/deji_new
          ansible-playbook -i ansible-config/inventory.yml ansible-config/playbook.yaml -v